name: Schema.org Validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  schema_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run schema.org validator
        run: |
          set -euo pipefail
          echo "Schema check started: $(date)"
          echo "URLs file: tests/urls.txt"
          python tests/schema_check.py | tee schema_check.log

      - name: Upload log as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: schema-validation-log
          path: schema_check.log
